apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: '{{ tfstate `azurerm_user_assigned_identity.workload.client_id` }}'
    keyvaultName: '{{ tfstate `azurerm_key_vault.example.name` }}'
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret
    tenantId: '{{ tfstate `data.azurerm_client_config.current.tenant_id` }}'
